import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import client from "../api/client";
import SeatMap from "../components/SeatMap";
import { Empty, ErrorMessage, Loading } from "../components/Feedback";
const fmt = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
export function Dashboard() { const [data, setData] = useState(null); useEffect(() => { client.get("/admin/dashboard").then((r) => setData(r.data)); }, []); if (!data) return <Loading/>; const cards = [["Total events", data.totalEvents], ["Upcoming", data.upcomingEvents], ["Confirmed tickets", data.confirmedBookings], ["Cancelled", data.cancelledBookings], ["Available seats", data.totalAvailableSeats], ["Revenue", fmt(data.totalRevenue)]]; return <section><p className="eyebrow">OVERVIEW</p><h1>Dashboard</h1><div className="stats">{cards.map(([name, value]) => <div className="stat" key={name}><span>{name}</span><strong>{value}</strong></div>)}</div><div className="panel"><div className="section-heading"><h2>Recent bookings</h2><Link to="/admin/bookings">View all</Link></div><BookingTable bookings={data.recentBookings}/></div></section>; }
export function AdminEvents() { const [events, setEvents] = useState(null); const [editing, setEditing] = useState(null); const [error, setError] = useState(""); const load = () => client.get("/admin/events").then((r) => setEvents(r.data)); useEffect(load, []); const remove = async (id) => { if (!confirm("Delete this event?")) return; try { await client.delete(`/events/${id}`); load(); } catch (e) { setError(e.response?.data?.message || "Could not delete event"); } }; if (!events) return <Loading/>; return <section><div className="section-heading"><div><p className="eyebrow">EVENT MANAGEMENT</p><h1>Events</h1></div><button onClick={() => setEditing({})}>Create event</button></div><ErrorMessage error={error}/>{editing && <EventForm initial={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load(); }}/>}<div className="list">{events.map((e) => <article className="booking-row" key={e._id}><span><strong>{e.title}</strong><small>{new Date(e.date).toLocaleDateString()} · {e.venue} · {e.availableSeats}/{e.totalSeats} open</small></span><span className="actions"><button className="secondary" onClick={() => setEditing(e)}>Edit</button><button className="danger" onClick={() => remove(e._id)}>Delete</button></span></article>)}</div></section>; }
function EventForm({ initial, onClose, onSaved }) { const [error, setError] = useState(""); const submit = async (e) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.target)); try { initial._id ? await client.put(`/events/${initial._id}`, data) : await client.post("/events", data); onSaved(); } catch (err) { setError(err.response?.data?.message || "Unable to save event"); } }; return <div className="modal"><form className="form-panel" onSubmit={submit}><h2>{initial._id ? "Edit event" : "Create event"}</h2><input name="title" placeholder="Event title" defaultValue={initial.title} required/><textarea name="description" placeholder="Description" defaultValue={initial.description} required/><input name="date" type="date" defaultValue={initial.date?.slice(0, 10)} required/><input name="time" type="time" defaultValue={initial.time} required/><input name="venue" placeholder="Venue" defaultValue={initial.venue} required/><input name="ticketPrice" type="number" min="0" placeholder="Ticket price" defaultValue={initial.ticketPrice} required/><input name="totalSeats" type="number" min="1" placeholder="Total seats" defaultValue={initial.totalSeats} required/><ErrorMessage error={error}/><div className="actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button>Save event</button></div></form></div>; }
export function AdminBookings() { const [bookings, setBookings] = useState(null); const [events, setEvents] = useState([]); const [query, setQuery] = useState(""); const load = (value = "") => client.get(`/admin/bookings?search=${encodeURIComponent(value)}`).then((r) => setBookings(r.data)); useEffect(() => { load(); client.get("/events").then((r) => setEvents(r.data)); }, []); if (!bookings) return <Loading/>; return <section><p className="eyebrow">BOOKING MANAGEMENT</p><h1>Bookings</h1><input className="search" placeholder="Search customer or event" value={query} onChange={(e) => { setQuery(e.target.value); load(e.target.value); }}/><BookingTable bookings={bookings}/>{events.length > 0 && <p className="muted">Use event detail pages to inspect visual seat availability.</p>}</section>; }
export function AdminUsers() { const [users, setUsers] = useState(null); useEffect(() => { client.get("/admin/users").then((r) => setUsers(r.data)); }, []); if (!users) return <Loading/>; return <section><p className="eyebrow">CUSTOMER MANAGEMENT</p><h1>Customers</h1>{users.length ? <div className="table"><div className="tr head"><span>Name</span><span>Email</span><span>Tickets</span><span>Active</span></div>{users.map((u) => <div className="tr" key={u._id}><span>{u.name}</span><span>{u.email}</span><span>{u.bookingSummary.total}</span><span>{u.bookingSummary.active}</span></div>)}</div> : <Empty>No registered customers.</Empty>}</section>; }
function BookingTable({ bookings }) { return bookings?.length ? <div className="table"><div className="tr head"><span>Customer</span><span>Event</span><span>Seats</span><span>Status</span></div>{bookings.map((b) => <div className="tr" key={b._id}><span>{b.user?.name || "—"}<small>{b.user?.email}</small></span><span>{b.event?.title || "—"}</span><span>{b.seats.join(", ")}</span><span className={`badge ${b.status.toLowerCase()}`}>{b.status}</span></div>)}</div> : <Empty>No bookings found.</Empty>; }
